#usuario:
#    resource: "@UsuarioBundle/Resources/config/routing.yml"
#    prefix:   /
#
#tienda:
#    resource: "@TiendaBundle/Resources/config/routing.yml"
#    prefix:   /
#
#ciudad:
#    resource: "@CiudadBundle/Resources/config/routing.yml"
#    prefix:   /
#
#oferta:
#    resource: "@OfertaBundle/Resources/config/routing.yml"
#    prefix:   /
#
#
#pagina_estatica:
#    pattern: /sitio/{pagina}
#    defaults: { _controller: OfertaBundle:Sitio:estatica}
#
## Ruta de la portada básica del sitio (sin ningún parámetro)
## esta ruta es opcional, ya que la aplicación puede funcionar bien
## solamente con la ruta 'portada' y sus valores por defecto
#_portada:
#     pattern:  /
#defaults: { _controller: FrameworkBundle:Redirect:redirect, route: portada, ciudad: '%cupon.ciudad_por_defecto%' }
#
#portada:
#    pattern:  /{ciudad}
#    defaults: { _controller: OfertaBundle:Default:portada }
#
#
## Internal routing configuration to handle ESI
## ****** WARNING ******
## This route should be enabled with caution as it can open a security vulnerability
## see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
## ****** WARNING ******
##_internal:
##    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
##    prefix:   /_internal
#


usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /


pagina_estatica:
    pattern: /sitio/{pagina}
    defaults: {_controller: OfertaBundle:Sitio:estatica}

portada:
    pattern: /
    defaults: {_controller: OfertaBundle:Default:portada}


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal